#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

buildpack=$1
buildpack_dir="$PLUSHU_BUILDPACKS_DIR/$buildpack"

# If the buildpack exists
if [[ -d "$buildpack_dir" ]]; then
  # Expose stdout on fd 3
  exec 3>&1

  # Retrieve it
  "$PLUSHU_ROOT/lib/plushook" update-dir "$buildpack_dir" "$buildpack" |
  while read -a update; do
    # If the buildpack was not updated
    if [[ -z "${update[1]}" ]]; then
    #  mention the system declaring it to be up to date
      echo "${update[0]}: $buildpack is up to date"
    fi
  done
fi
