#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# create PLUSHU_BUILDPACKS_DIR
mkdir -p "$PLUSHU_ROOT/buildpacks"
if [[ "$EUID" == 0 ]]; then
  chown -R "$PLUSHU_USER:" "$PLUSHU_ROOT/buildpacks"
fi
