#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# Update each buildpack to update
for buildpack in "$PLUSHU_BUILDPACKS_DIR"/*; do
  "$PLUSHU_ROOT/lib/plushook" update-buildpack "${buildpack##*/}"
done
