#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

buildpack=$1
remote=$2

buildpack_dir=$PLUSHU_BUILDPACKS_DIR/$buildpack

# If the buildpack doesn't already exist
if [[ ! -e "$buildpack_dir" ]]; then

  # Retrieve it
  "$PLUSHU_ROOT/lib/plushook" retrieve-dir "$buildpack_dir" "$remote"

  # If the buildpack was not downloaded
  if [[ ! -e "$buildpack_dir" ]]; then
    echo "URL could not be retrieved: $remote" >&2
    exit 1
  else
    # Notify that the buildpack has been installed
    echo "Buildpack '$buildpack' installed."
  fi
fi
