#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

buildpack=$1
buildpack_dir=$PLUSHU_BUILDPACKS_DIR/$buildpack

# If the buildpack exists
if [[ -d "$buildpack_dir" ]]; then

  # Remove the buildpack
  rm -rf "$buildpack_dir"
  echo "Buildpack '$buildpack' uninstalled."
fi
